version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    networks:
      - sc-network
volumes:
  postgres-vol:
networks:
  sc-network: