security:
  jwt:
    token:
      secret-key: 53ccr37
      expire-length: 3600000

spring:
  datasource:
    url: jdbc:postgresql://ec2-44-215-1-253.compute-1.amazonaws.com:5432/d4v5m3bd8fo918?useTimezone=true&serverTimezone=UTC
    username: llvhzeprtvyrbi
    password: a293b054d5838972b0e8b14b3519300c9370cc875d2f94ff0cc33e3b0a3886f8
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: suporte.teste.catolica@gmail.com
    password: fzzf sjab fpqk couk
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
springdoc:
  pathsToMatch:
    - /auth/**
    - /api/**/v1/**
